name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-js:
        runs-on: ubuntu-latest
        container:
            image: node:20
        steps:
            - uses: actions/checkout@v3
              with:
                node-version: 20
            - run: npm ci
            - run: npm test
            - run: npm run build
            - run: export DATABASE_URL="postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@localhost:5433/socialnetwork"
